site_name: frikiteam Docs
site_url: https://docs.frikiteam.es
site_description: Documentaci贸n oficial del proyecto frikiteam 
nav:
  - Home: index.md
  - Documentaci贸n t茅cnica: 
    - Ansible: doc/ansible/ansible_base.md
    - Ceph: doc/ceph/ceph_base.md
    - Docker: doc/docker/docker_base.md
    - Kubernetes: doc/kubernetes/kubernetes_base.md
    - OpenStack: doc/openstack/openstack_base.md
    - Terraform: doc/terraform/terraform_base.md
  # - Blog: 
  #   - blog/index.md
  - Acerca de: about.md
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: 'es'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.instant.progress
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.share
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - attr_list
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

plugins: 
  - search
  - social
  - minify
  # - i18n:
  #     default_language: es
  #     languages:
  #       es: Espa帽ol
  #       en: English
  # - blog: 
  #     authors_file: "blog/authors/.authors.yml"
extra:
  consent:
    title: Consentimiento de cookies
    description: >- 
      Usamos cookies para reconocer tus visitas y preferencias repetidas, as铆 
      como para medir la efectividad de nuestra documentaci贸n y si los usuarios 
      encuentran lo que buscan. Con tu consentimiento, nos ayudas a mejorar 
      nuestra documentaci贸n.
  alternate:
    - name: English
      link: /en/ 
      lang: en
  # analytics:
  #   provider: google
  #   property: G-X41K5YEY4S